spring.application.name=inventory-manager

# MySQL - XAMPP (solo MySQL activo, Apache no es necesario)
spring.datasource.url=jdbc:mysql://localhost:3306/inventario?useSSL=false&serverTimezone=America/Mexico_City&allowPublicKeyRetrieval=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=

# JPA / Hibernate (dialecto auto-detectado, no se especifica)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# Servidor en puerto 8080
server.port=8080
#acceso desde otros dispositivos al servidor
server.address=0.0.0.0

# URL base de la aplicación (usada en correos de recuperación de contraseña)
app.base-url=http://172.17.192.1:8080
